### ISSUE TITLE
Problema ao visualizar erro de retorno do servidor.

### ISSUE THREAD

**Issue by sistechgithub** [sistechgithub/backup-gpweb#7]
Até o seguinte commit realizado por @jacksondeveloper :

Id: 2eeb7e1de4107f8b3d6f08dc32bfc4290efff383
Author: jacksondeveloper jackson.jack.sth@gmail.com
Date:   Fri Jan 22 08:44:16 2016 -0300
Alteração:  Regra de negócio para o cadastro de grupos

O sistema apresentava a mensagem de erro que vinha do servidor, como por exemplo tentamos incluir um grupo com uma descrição já existente (o que é o desejável apesar da mensagem ainda não está sendo tratada).

Porém logo após este commit, provavelmente devido a um commit de Ronaldo com um merge das alterações de Ytalo, o front-end não está mais mostrando a mensagem de erro, deixando a tela de cadastro se nenhuma action. (É até possível visualizar o erro no front-end pelo console JavaScript do navegador).

Peço aos senhores @ronaldofilhosth  e @YtaloLemos que analisem e se possível corrijam.

**Comment by jacksondeveloper** [comment]
Com o commit: 2169595ac38397c2a252dd375ea6bf5622cab48a
estou corrigindo o problema, voltando a versão do alert.directive.js e adicionando o código novo de @ronaldofilhosth juntamente com ele, corrigindo alguns conflitos.
